import CustomError from './customerror';
export const userNotFoundError = new CustomError('User Not Found', 415);
